# Generated by Django 2.1.8 on 2019-06-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='study_category',
            field=models.CharField(default='ALL', max_length=50),
        ),
    ]
