# Generated by Django 2.1.8 on 2019-06-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='summary',
            new_name='hashtags',
        ),
    ]
