# Generated by Django 2.1.8 on 2019-06-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='post',
            name='hash_tag_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hash_tag',
            field=models.ManyToManyField(blank=True, related_name='match_room_tagged', to='posts.HashTag'),
        ),
    ]
