# Generated by Django 2.1.8 on 2019-06-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
