# Generated by Django 2.1.8 on 2019-06-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190625_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='study_category',
            field=models.CharField(choices=[('python', 'Python'), ('r', 'R'), ('c', 'C'), ('java', 'Java')], max_length=10),
        ),
    ]
