# Generated by Django 2.1.8 on 2019-06-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_category', models.CharField(choices=[('python', 'Python'), ('r', 'R'), ('java', 'Java')], max_length=10)),
                ('number_people', models.IntegerField()),
                ('study_place', models.CharField(choices=[('강남', '강남역'), ('교대', '교대역'), ('역삼', '역삼역')], max_length=10)),
                ('study_day', models.CharField(choices=[('주1회', '주1회'), ('주2회', '주2회'), ('주3회', '주3회'), ('협의', '협의')], max_length=10)),
                ('study_time', models.CharField(choices=[('1hour', '1hour'), ('2hour', '2hour'), ('3hour', '3hour')], max_length=10)),
            ],
        ),
    ]
