# Generated by Django 2.1.8 on 2019-06-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchpost',
            name='number_people',
        ),
        migrations.RemoveField(
            model_name='matchpost',
            name='study_category',
        ),
        migrations.RemoveField(
            model_name='matchpost',
            name='study_day',
        ),
        migrations.RemoveField(
            model_name='matchpost',
            name='study_place',
        ),
        migrations.RemoveField(
            model_name='matchpost',
            name='study_time',
        ),
        migrations.AddField(
            model_name='matchpost',
            name='category',
            field=models.CharField(choices=[('python', 'python'), ('r', 'r'), ('c', 'c'), ('java', 'java')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchpost',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchpost',
            name='place',
            field=models.CharField(choices=[('강남역', '강남역'), ('교대역', '교대역'), ('역삼역', '역삼역')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
