# Generated by Django 2.1.8 on 2019-06-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20190623_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpost',
            name='hash_tag_list',
            field=models.TextField(blank=True),
        ),
    ]
