# Generated by Django 2.1.8 on 2019-06-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_matchpost_hash_tag_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpost',
            name='content_token',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
