# Generated by Django 2.1.8 on 2019-06-25 05:45

from django.conf import settings
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='accounts/images'),
        ),
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pick',
            field=models.ManyToManyField(related_name='picker', to=settings.AUTH_USER_MODEL),
        ),
    ]
